export const GET_HOME_DASHBOARD_STATS = 'GET_HOME_DASHBOARD_STATS'
export const GET_HOME_DASHBOARD_STATS_SUCCESS = 'GET_HOME_DASHBOARD_STATS_SUCCESS'
export const GET_HOME_DASHBOARD_STATS_FAILED = 'GET_HOME_DASHBOARD_STATS_FAILED'
